-- MySQL Script generated by MySQL Workbench
-- Wed Mar  4 08:36:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema examentalent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examentalent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examentalent` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `idAlumno` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `idProfesor` INT NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asignatura` (
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`, `Asignatura_idAsignatura`, `Profesor_idProfesor`),
  INDEX `fk_Asignatura_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `mydb`.`profesor` (`idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `codigo` INT NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_curso_Asignatura1_idx` (`Asignatura_idAsignatura` ASC, `Asignatura_Asignatura_idAsignatura` ASC, `Asignatura_Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_curso_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura` , `Asignatura_Asignatura_idAsignatura` , `Asignatura_Profesor_idProfesor`)
    REFERENCES `mydb`.`asignatura` (`idAsignatura` , `Asignatura_idAsignatura` , `Profesor_idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aula` (
  `numeroAula` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `curso_codigo` INT NOT NULL,
  PRIMARY KEY (`numeroAula`, `curso_codigo`),
  INDEX `fk_aula_curso1_idx` (`curso_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_aula_curso1`
    FOREIGN KEY (`curso_codigo`)
    REFERENCES `mydb`.`curso` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cusa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cusa` (
  `Alumno_idAlumno` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Profesor_idProfesor` INT NOT NULL,
  `examen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Alumno_idAlumno`, `Asignatura_idAsignatura`, `Asignatura_Asignatura_idAsignatura`, `Asignatura_Profesor_idProfesor`),
  INDEX `fk_Alumno_has_Asignatura_Asignatura1_idx` (`Asignatura_idAsignatura` ASC, `Asignatura_Asignatura_idAsignatura` ASC, `Asignatura_Profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Asignatura_Alumno1_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Asignatura_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `mydb`.`alumno` (`idAlumno`),
  CONSTRAINT `fk_Alumno_has_Asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura` , `Asignatura_Asignatura_idAsignatura` , `Asignatura_Profesor_idProfesor`)
    REFERENCES `mydb`.`asignatura` (`idAsignatura` , `Asignatura_idAsignatura` , `Profesor_idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `examentalent` ;

-- -----------------------------------------------------
-- Table `examentalent`.`entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examentalent`.`entrenador` (
  `id_entrenador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`id_entrenador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examentalent`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examentalent`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `anyo_fundacion` INT NULL,
  `entrenador_id_entrenador` INT NOT NULL,
  PRIMARY KEY (`id_equipo`),
  UNIQUE INDEX `id_equipo_UNIQUE` (`id_equipo` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_equipo_entrenador1_idx` (`entrenador_id_entrenador` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_entrenador1`
    FOREIGN KEY (`entrenador_id_entrenador`)
    REFERENCES `examentalent`.`entrenador` (`id_entrenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examentalent`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examentalent`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NULL,
  `edad` INT NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  PRIMARY KEY (`id_jugador`),
  INDEX `fk_jugador_equipo_idx` (`equipo_id_equipo` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_equipo`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `examentalent`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
